# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  authorizationserver:
    image: authorizationserver:debug
    build:
      context: .
      dockerfile: ./src/AuthorizationServer/Dockerfile
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/v2_dev_cert.pfx
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ~/.aspnet/https:/https:ro
  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_DATABASE=foundant
      - MONGO_INITDB_ROOT_USERNAME=foundant_debug
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017-27019:27017-27019"